POST http://localhost:3333/events
Content-Type: application/json


{
    "title":"Evento",
    "details":null,
    "maximumAttendees":1
}

###

POST http://localhost:3333/events/17b5fe27-a97a-4341-a7c0-d0b2fcb826cb/attendees
Content-Type: application/json

{
    "name":"Diego fernandes",
    "email":"diego2@rockeseat.com.br"
}

###

GET http://localhost:3333/events/17b5fe27-a97a-4341-a7c0-d0b2fcb826cb


###
GET http://localhost:3333/attendees/9/badge

###
GET http://localhost:3333/attendees/9/check-in

###
GET http://localhost:3333/events/17b5fe27-a97a-4341-a7c0-d0b2fcb826cb/attendees?query=diego